### PR TITLE
Fix react typing

### PR DESCRIPTION
**Pull request by palmenhq**
Hello! Thanks for a really great lib! Unfortunately the type definition causes some minor typescript issues if `allowSyntheticDefaultImports` is not enabled:

```
node_modules/storyblok-react/lib/sb-editable.d.ts:1:8 - error TS1259: Module '".../node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

1 import React from 'react'
         ~~~~~

  node_modules/@types/react/index.d.ts:62:1
    62 export = React;
       ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

myFile.tsx:30:15 - error TS2605: JSX element type 'SbEditable' is not a constructor function for JSX elements.
  Type 'SbEditable' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, and 2 more.

30               <SbEditable content={block}  key={block._uid}>
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

myFile.tsx:30:15 - error TS2607: JSX element class does not support attributes because it does not have a 'props' property.

30               <SbEditable content={block}  key={block._uid}>
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[10:52:17 AM] Found 3 errors.
```

Unsure whether this is the optimal solution, but it works on my machine ™ 😄

### CODE REVIEW

**Comment by emanuelgsouza** [comment]
Hi, thanks for submitting this PR and sorry for the late reply. Could you check if these errors continue to occur?

**Comment by fgiuliani** [comment]
Hi @palmenhq we've changed the approach for this package. Could you take a look at how the @storyblok/react package works?

We'll be adding TypeScript support soon for that package.

**Comment by palmenhq** [comment]
@fgiuliani Nice! I can take a look in the coming days and toy a little bit with it if you want? Anything specific you're looking for or just general feedback?

**Comment by fgiuliani** [comment]
Hey @palmenhq thanks for your response!
We're not looking for anything specific. Just wanted to check with you If you had the chance to see the new SDK 😊
If you play with it, or you use it in any project, we'll be happy to know your thoughts!

Also, ask you since we have a new SDK, if this PR still makes sense 🤔

**Comment by palmenhq** [comment]
@fgiuliani Perfect, i'll make time for some exploration. I'm no longer using storyblok for production (as i've switched jobs) but i'm happy to toy with it!

And no, i don't think this pr makes sense. I'll close it and open any new issue if i find any improvement areas in the new api 👍

**Pull request closed without merging**
